modLoader = "javafml"
loaderVersion = "[47,)"
license = "Apache-2.0"

[[mods]]
modId = "portable_api_validation"
version = "${version}"
displayName = "Portable API Validation"
description = '''Blank validation consumer for Portable API.'''

[[dependencies.portable_api_validation]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.portable_api_validation]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.portable_api_validation]]
modId = "portable_api"
mandatory = true
versionRange = "[${version},)"
ordering = "AFTER"
side = "BOTH"
