package dev.portablemc.api.runtime;

/** Portable API v1 feature areas. */
public enum Capability {
  LIFECYCLE_EVENTS,
  LOGGING,
  ENVIRONMENT,
  SIDED_EXECUTION,
  CONFIGURATION,
  COMMANDS,
  REGISTRIES,
  REGISTRY_SUPPLIERS,
  CREATIVE_TAB_POPULATION,
  RESOURCES,
  NETWORKING,
  DATA_ATTACHMENTS,
  CLIENT_INITIALIZATION,
  SERVER_INITIALIZATION,
  RAW_MINECRAFT_ACCESS,
  WORLDGEN,
  SCREEN_REGISTRATION,
  RENDERING,
  MIXIN_OR_TRANSFORMER_BRIDGES
}
